# Generated by Django 5.0.7 on 2024-07-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='center_x',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='center_y',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='height',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='width',
            field=models.FloatField(default=0, null=True),
        ),
    ]
