# Generated by Django 5.0.7 on 2024-07-15 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_zone_center_x_zone_center_y_zone_height_zone_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='index',
            new_name='slug',
        ),
    ]
