# Generated by Django 5.0.7 on 2024-07-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_rename_index_zone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
    ]
