# Generated by Django 5.0.7 on 2024-07-16 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_family_tracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.family'),
        ),
    ]
