# Generated by Django 5.0.7 on 2024-07-16 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_alter_family_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuration.family'),
        ),
    ]
