# Generated by Django 5.0.7 on 2024-07-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_alter_family_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='trigger',
            field=models.BooleanField(default=False),
        ),
    ]
