# Generated by Django 5.0.7 on 2024-07-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_rule_family_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_abstract',
            field=models.BooleanField(default=False),
        ),
    ]
