# Generated by Django 5.0.7 on 2024-07-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_family_is_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='tracked',
            new_name='is_tracked',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='trigger',
            new_name='is_trigger',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='trigger',
        ),
        migrations.AddField(
            model_name='zone',
            name='is_tracked',
            field=models.BooleanField(default=False),
        ),
    ]
