# Generated by Django 5.0.7 on 2024-07-18 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_rename_tracked_family_is_tracked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='is_tracked',
            new_name='is_trigger',
        ),
    ]
