# Generated by Django 5.0.7 on 2024-07-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_rename_is_tracked_zone_is_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'families'},
        ),
        migrations.AddField(
            model_name='family',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
