# Generated by Django 5.0.7 on 2024-07-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_alter_family_options_family_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_ignored',
            field=models.BooleanField(default=False),
        ),
    ]
