# Generated by Django 5.0.7 on 2024-07-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0015_zone_is_ignored'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_zoned',
            field=models.BooleanField(default=False),
        ),
    ]
