# Generated by Django 5.0.7 on 2024-07-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_family_is_zoned'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='color',
            field=models.CharField(choices=[('6f4e37', 'Coffee'), ('e23e28', 'Chill red'), ('ffbf00', 'Amber'), ('ffffff', 'White')], max_length=100, null=True),
        ),
    ]
