# Generated by Django 5.0.7 on 2024-08-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0018_parameter_period_remove_rule_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
