# Generated by Django 5.0.7 on 2024-08-29 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0019_alter_parameter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('level', models.CharField(default='', max_length=200, null=True)),
                ('event', models.CharField(default='', max_length=200, null=True)),
                ('info', models.CharField(default='', max_length=200, null=True)),
                ('temp', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
