# Generated by Django 5.0.7 on 2024-08-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0020_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='source',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
