# Generated by Django 5.0.7 on 2024-09-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0021_log_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_indoor',
            field=models.BooleanField(default=False),
        ),
    ]
