# Generated by Django 5.0.7 on 2024-09-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0022_zone_is_indoor'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
