# Generated by Django 5.0.7 on 2024-09-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0023_zone_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='version',
        ),
    ]
