# Generated by Django 5.0.7 on 2024-09-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0024_remove_log_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='temp',
        ),
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('event', 'Event'), ('statistic', 'Statistic'), ('warning', 'Warning'), ('temp', 'Temp'), ('error', 'Error'), ('fail', 'Fail')], default='info', max_length=200, null=True),
        ),
    ]
