# Generated by Django 5.0.7 on 2024-09-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0025_remove_log_temp_alter_log_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(choices=[('vision', 'Vision'), ('video', 'Video'), ('photo', 'Photo')], default='vision', max_length=200, null=True),
        ),
    ]
