# Generated by Django 5.0.7 on 2024-10-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0026_alter_log_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('event', 'Event'), ('statistic', 'Statistic'), ('warning', 'Warning'), ('hot', 'Hot'), ('error', 'Error'), ('fail', 'Fail')], default='info', max_length=200, null=True),
        ),
    ]
