# Generated by Django 5.0.7 on 2025-01-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0027_alter_log_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
