# Generated by Django 5.0.7 on 2025-02-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0028_family_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
