# Generated by Django 5.0.7 on 2025-04-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0029_family_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('local', 'Local'), ('info', 'Info'), ('event', 'Event'), ('statistic', 'Statistic'), ('warning', 'Warning'), ('hot', 'Hot'), ('error', 'Error'), ('fail', 'Fail')], default='info', max_length=200, null=True),
        ),
    ]
