[uwsgi]
project = admin
uid = jaden
base = /home/%(uid)/Projects/followchon_back

chdir = %(base)
home = %(base)/venv
module = %(project).wsgi:application
static-map = /static=%(base)/static

master = true
processes = 5

#http-socket = :8080

socket = /run/uwsgi/%(project).sock
chown-socket = %(uid):www-data
chmod-socket = 660
vacuum = true
