# Generated by Django 5.0.7 on 2024-07-12 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('photo_file', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_x', models.FloatField(default=0, null=True)),
                ('center_y', models.FloatField(default=0, null=True)),
                ('width', models.FloatField(default=0, null=True)),
                ('height', models.FloatField(default=0, null=True)),
                ('score', models.IntegerField(default=0, null=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.capture')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.family')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.zone')),
            ],
        ),
    ]
