# Generated by Django 5.0.7 on 2024-07-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='capture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detections.capture'),
        ),
    ]
