# Generated by Django 5.0.7 on 2024-07-15 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_zone_center_x_zone_center_y_zone_height_zone_width'),
        ('detections', '0002_alter_detection_capture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='verified',
        ),
        migrations.AddField(
            model_name='capture',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('archived', 'Archived')], default='draft', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuration.family'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.zone'),
        ),
    ]
