# Generated by Django 5.0.7 on 2024-07-16 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0003_remove_capture_verified_capture_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
