# Generated by Django 5.0.7 on 2024-07-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0004_alter_capture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='trigger',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
