# Generated by Django 5.0.7 on 2024-07-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0005_detection_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='center_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='center_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
