# Generated by Django 5.0.7 on 2024-07-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0006_alter_detection_center_x_alter_detection_center_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='trigger',
            field=models.CharField(choices=[('move', 'Move'), ('zone', 'Zone'), ('family', 'Family')], max_length=100, null=True),
        ),
    ]
