# Generated by Django 5.0.7 on 2024-07-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0007_alter_detection_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=200, null=True),
        ),
    ]
