# Generated by Django 5.0.7 on 2024-07-29 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_family_color'),
        ('detections', '0008_alter_capture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='zone',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.zone'),
        ),
    ]
