# Generated by Django 5.0.7 on 2024-07-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0009_alter_detection_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='trigger',
            field=models.CharField(choices=[('move', 'Move'), ('zone', 'Zone'), ('family', 'Family')], default=None, max_length=100, null=True),
        ),
    ]
