# Generated by Django 5.0.7 on 2024-07-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0010_alter_detection_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='center_x',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='center_y',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='height',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='score',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='width',
            field=models.FloatField(default=0, null=True),
        ),
    ]
