# Generated by Django 5.0.7 on 2024-08-27 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0018_parameter_period_remove_rule_enabled_and_more'),
        ('detections', '0011_alter_detection_center_x_alter_detection_center_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detections', to='configuration.family'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='trigger',
            field=models.CharField(choices=[('move', 'Move'), ('zone', 'Zone'), ('family', 'Family')], max_length=100, null=True),
        ),
    ]
