# Generated by Django 5.0.7 on 2024-09-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0012_alter_detection_family_alter_detection_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
