# Generated by Django 5.0.7 on 2024-09-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0014_capture_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='source',
            field=models.CharField(choices=[('vision', 'Vision'), ('video', 'Video'), ('photo', 'Photo')], default='vision', max_length=200, null=True),
        ),
    ]
