# Generated by Django 5.0.7 on 2025-01-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0015_capture_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='version_train',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
