# Generated by Django 5.0.7 on 2025-01-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0016_capture_version_train'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='version_train',
        ),
        migrations.AddField(
            model_name='capture',
            name='train_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capture',
            name='train_chons',
            field=models.BooleanField(default=False),
        ),
    ]
