# Generated by Django 5.0.7 on 2025-01-03 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0027_alter_log_level'),
        ('detections', '0017_remove_capture_version_train_capture_train_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='trigger',
            field=models.CharField(blank=True, choices=[('move', 'Move'), ('zone', 'Zone'), ('family', 'Family')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='zone',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.zone'),
        ),
    ]
