# Generated by Django 5.0.7 on 2025-01-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0018_alter_detection_score_alter_detection_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='version_classify',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
