# Generated by Django 5.0.7 on 2025-01-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0019_capture_version_classify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capture',
            old_name='version',
            new_name='version_detect',
        ),
    ]
