# Generated by Django 5.0.7 on 2025-05-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0020_rename_version_capture_version_detect'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='errors',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='capture',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified'), ('archived', 'Archived'), ('waiting', 'Waiting'), ('deleted', 'Deleted')], default='draft', max_length=200, null=True),
        ),
    ]
